<a href="https://colab.research.google.com/github/Ayushnegi317/EDA-projects/blob/main/zomato.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import plotly.express as pl
import seaborn as sns
import matplotlib.pyplot as plt

**Objective**
1.To finding out and analysis of different reviews of customers in Cuisines 
2.Restaurant in which Country and Cities have best and poor food 
To find out highest Transaction Activities in different Countries And Cities

In [ ]:
#dataset
df=pd.read_excel("/content/zomato updated data.xlsx")
df

,Restaurant ID,Restaurant Name,Country Code,Country,City,Address,Locality,Locality Verbose,Longitude,Latitude,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Phillipines,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,...,Botswana Pula(P),Yes,No,No,No,3.0,4.8,Dark Green,Excellent,314.0
1,6304287,Izakaya Kikufuji,162,Phillipines,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,...,Botswana Pula(P),Yes,No,No,No,3.0,4.5,Dark Green,Excellent,591.0
2,6300002,Heat - Edsa Shangri-La,162,Phillipines,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,...,Botswana Pula(P),Yes,No,No,No,4.0,4.4,Green,Very Good,270.0
3,6318506,Ooma,162,Phillipines,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,...,Botswana Pula(P),No,No,No,No,4.0,4.9,Dark Green,Excellent,365.0
4,6314302,Sambo Kojin,162,Phillipines,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,...,Botswana Pula(P),Yes,No,No,No,4.0,4.8,Dark Green,Excellent,229.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,Turkey,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,...,Turkish Lira(TL),No,No,No,No,3.0,4.1,Green,Very Good,788.0
9547,5908749,Ceviz AÛôacÛ±,208,Turkey,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,...,Turkish Lira(TL),No,No,No,No,3.0,4.2,Green,Very Good,1034.0
9548,5915807,Huqqa,208,Turkey,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,...,Turkish Lira(TL),No,No,No,No,4.0,3.7,Yellow,Good,661.0
9549,5916112,Aôôk Kahve,208,Turkey,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,...,Turkish Lira(TL),No,No,No,No,4.0,4.0,Green,Very Good,901.0
9550,5927402,Walter's Coffee Roastery,208,Turkey,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,...,Turkish Lira(TL),No,No,No,No,2.0,4.0,Green,Very Good,591.0

In [ ]:
# No. of columns
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'Country', 'City',
       'Address', 'Locality', 'Locality Verbose', 'Longitude', 'Latitude',
       'Cuisines', 'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [ ]:
#Total ratings
df.value_counts("Rating text")

Rating text
Average      3735
Not rated    2146
Good         2098
Very Good    1079
Excellent     301
Poor          186
dtype: int64

In [ ]:
#find poor rating in City Country
df1=df.groupby("Rating text")

In [ ]:
Poor=df1.get_group("Poor")
verdict1=Poor.value_counts("City")

In [ ]:
verdict2=Poor.value_counts("Country")

In [ ]:
verdict3=Poor.value_counts("Cuisines")

In [ ]:
verdict4=Poor.value_counts("Restaurant Name")
print(verdict1,"  ",verdict2,"  ",verdict3,"  ",verdict4,sep="\n")

City
New Delhi      97
Noida          45
Gurgaon        34
Faridabad       2
Auckland        1
Colombo         1
Gainesville     1
Ghaziabad       1
Mc Millan       1
Montville       1
Nagpur          1
Sharjah         1
dtype: int64

Country
India            180
United States      2
Australia          1
New Zealand        1
Sri Lanka          1
UAE                1
dtype: int64

Cuisines
North Indian, Chinese             17
Pizza, Fast Food                  13
North Indian                      11
North Indian, Mughlai, Chinese     9
North Indian, Mughlai              9
                                  ..
Italian, European                  1
American, Fast Food                1
Lebanese, Chinese, Fast Food       1
Lucknowi, Mughlai                  1
Tea, Fast Food                     1
Length: 73, dtype: int64

Restaurant Name
Domino's Pizza             12
Subway                      7
Wah Ji Wah                  7
Pizza Hut Delivery          5
Sagar Ratna                 4
                           ..
Elite Indian Restaurant     1
Dilli Darbar                1
Deltasious                  1
Delhi Darbar                1
Zustt Yummy                 1
Length: 132, dtype: int64

**Observation**


*  Top poor rated in country is india
*  Top 3 Cities are poor rated
   New Delhi
   Noida          
   Gurgaon 

*  Top 3 poor rated cuisines are
North Indian, Chinese             
Pizza, Fast Food, North Indian 


* Top 5 restaurant are poor rated Domino's Pizza           ,Subway,Wah Ji Wah,Pizza Hut Delivery,Sagar Ratna

In [ ]:
#lets find the highly Rated by City,Cuisines,Restaurant Name,Country
Excellent=df1.get_group("Excellent")
Rate=Excellent.value_counts("Country")

In [ ]:
Rate1=Excellent.value_counts("City")

In [ ]:
Rate2=Excellent.value_counts("Cuisines")

In [ ]:
Rate3=Excellent.value_counts("Restaurant Name")

In [ ]:
print(Rate,"  ",Rate1,"  ",Rate2,"  ",Rate3,sep="\n")

Country
India             116
United States      68
United Kingdom     23
UAE                18
Brazil             16
New Zealand        12
Phillipines        12
South Africa       12
Turkey             10
Indonesia           7
Qatar               4
Sri Lanka           2
Australia           1
dtype: int64

City
New Delhi         28
London            15
Gurgaon           12
Rio de Janeiro    11
Tampa Bay         10
                  ..
Quezon City        1
Faridabad          1
Beechworth         1
Agra               1
Johannesburg       1
Length: 74, dtype: int64

Cuisines
Cafe              8
Italian           7
North Indian      7
Indian            5
Ice Cream         5
                 ..
Chinese, Pizza    1
Chinese, Steak    1
Chinese, Thai     1
Contemporary      1
World Cuisine     1
Length: 214, dtype: int64

Restaurant Name
Barbeque Nation                   11
AB's - Absolute Barbecues          4
Chili's                            4
Talaga Sampireun                   3
Big Chill                          2
                                  ..
Hobing Korean Dessert Cafe         1
Hollerbach's Willow Tree Cafí©     1
Hot Palayok                        1
Huber & Holly                      1
sketch Gallery                     1
Length: 272, dtype: int64

**Obersvation**
* Top highly rated food in country wise are 

  India             
United States      
United Kingdom     
UAE                
Brazil  
* Top Highly Rated Food in cities

  New Delhi         
London            
Gurgaon           
Rio de Janeiro    
Tampa Bay


* Top Highly Rated Cusines 

  Cafe              
Italian           
North Indian      
Indian            
Ice Cream


* Top Highly Rated Restuarant

  Barbeque Nation                  
AB's - Absolute Barbecues          
Chili's                           
Talaga Sampireun                   
Big Chill

In [ ]:
#finding out the Average Rating in different categories
Average=df1.get_group("Average")
avg=Average.value_counts('Country')
avg1=Average.value_counts('City')
avg2=Average.value_counts('Cuisines')
avg3=Average.value_counts('Restaurant Name')
print(avg,"   ",avg1,"   ",avg2,"   ",avg3,sep="\n")

Country
India             3677
United States       23
Brazil               8
Singapore            8
United Kingdom       5
Australia            4
Canada               2
Qatar                2
Sri Lanka            2
Indonesia            1
South Africa         1
Turkey               1
UAE                  1
dtype: int64

City
New Delhi         2494
Gurgaon            504
Noida              449
Faridabad          123
Ghaziabad           18
Aurangabad          16
Allahabad           15
Ranchi              11
Patna                9
Varanasi             8
Singapore            8
Nashik               8
Albany               7
Brasí_lia            6
Amritsar             5
Dubuque              5
Manchester           3
Kanpur               3
Birmingham           2
Chandigarh           2
Mysore               2
Bhopal               2
Puducherry           2
Doha                 2
Colombo              2
Valdosta             2
Sí£o Paulo           2
Pretoria             1
Surat                1
Potrero              1
Penola               1
Paynesville          1
Waterloo             1
Winchester Bay       1
Savannah             1
Agra                 1
Nagpur               1
Mumbai               1
Miller               1
Mayfield             1
Jakarta              1
Jaipur               1
Indore               1
Dubai                1
Des Moines           1
Davenport            1
Consort              1
Columbus             1
Cochrane             1
Balingup             1
Ankara               1
Yorkton              1
dtype: int64

Cuisines
North Indian                                366
North Indian, Chinese                       303
North Indian, Mughlai                       185
Fast Food                                   151
Chinese                                     151
                                           ...
Fast Food, American, Salad, Healthy Food      1
Fast Food, American                           1
European, Sushi, Italian                      1
European, North Indian                        1
Western, Fusion, Fast Food                    1
Length: 604, dtype: int64

Restaurant Name
Cafe Coffee Day                   59
Domino's Pizza                    53
Subway                            43
Green Chick Chop                  40
McDonald's                        27
                                  ..
Goosebumps                         1
Gopal (Sindhi) Restaurant          1
Gopal's                            1
Gopal's Restaurant & Caterer's     1
iGNiTE                             1
Length: 2926, dtype: int64

**Observation**


*  Top Average Rated Food in Country wise

 India             
United States        
*  Top Average Food in Cities in City wise

 New Delhi
Gurgaon            
Noida              
Faridabad          
Ghaziabad           

* Top Average Rated Cuisines

 North Indian                                
North Indian, Chinese                      
North Indian, Mughlai                       
Fast Food                                  
Chinese            
* Top Average Rated Restaurant

  Cafe Coffee Day                   
Domino's Pizza                    
Subway                            
Green Chick Chop                  
McDonald's

In [ ]:
#good rated in different categories
Verygood=df1.get_group("Very Good")
Verygood0=Verygood.value_counts('Country')
Verygood1=Verygood.value_counts('City')
Verygood2=Verygood.value_counts('Cuisines')
Verygood3=Verygood.value_counts('Restaurant Name')
print(Verygood0,"   ",Verygood1,"   ",Verygood2,"   ",Verygood3,sep="\n")

Country
India             692
United States     179
South Africa       35
UAE                31
United Kingdom     31
New Zealand        25
Brazil             20
Turkey             20
Sri Lanka          11
Indonesia          10
Phillipines         9
Qatar               7
Australia           5
Singapore           3
Canada              1
dtype: int64

City
New Delhi          300
Gurgaon             83
Noida               27
Wellington City     16
Boise               16
                  ...
Mohali               1
Princeton            1
Huskisson            1
Randburg             1
East Ballina         1
Length: 96, dtype: int64

Cuisines
Cafe                               28
North Indian, Mughlai              25
Chinese                            21
North Indian, Chinese              19
Italian                            18
                                   ..
Contemporary, Burger, European      1
Continental, American, Cafe         1
Continental, American, Italian      1
Continental, American, Seafood      1
World Cuisine, Patisserie, Cafe     1
Length: 645, dtype: int64

Restaurant Name
Barbeque Nation               12
Pizza Hut                      6
Farzi Cafe                     5
Mocha                          4
Punjab Grill                   4
                              ..
Free Spirit                    1
French Toast                   1
Freshco - The Health Cafí©     1
Frog Hollow Tavern             1
íˆukuraÛôa SofrasÛ±            1
Length: 987, dtype: int64

**Observation**

*   Top Good Rated Food in Country Wise

 India             
United States     
South Africa       
UAE                
United Kingdom     
* Top Good Rated Food in City wise

 New Delhi          
Gurgaon             
Noida               
Wellington City     
Boise   


* Top Good Rated Cuisines 

 Cafe                               
North Indian, Mughlai              
Chinese                           
North Indian, Chinese              
Italian 
* Top Good Rated Restaurant

 Barbeque Nation              
Pizza Hut                      
Farzi Cafe                    
Mocha                          
Punjab Grill

In [ ]:
#now finding the highest transaction in No. of Countries
currency=df.groupby(["Country","Currency"]).size().reset_index(name="No. of Transaction")

In [ ]:
pl.pie(currency,values='No. of Transaction',labels="Currency",color="Country",title="Most Transaction in Country")

**Observation**

Most Transaction have been done in India and then USA

In [ ]:
#highest transaction in Cities
currency1=df.groupby(["City","Currency"]).size().reset_index(name="No. of Transaction")

In [ ]:
pl.histogram(currency1,x="City",y="No. of Transaction",title="Most Transaction in City")

**Observation**
Most Transaction in have been done in cities are 

New Delhi

Noida

Gurgaon